#pragma once

#define EE_HANDS

#define TAPPING_TERM 200
#define IGNORE_MOD_TAP_INTERRUPT

#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_COLOR
#define RGB_MATRIX_STARTUP_SAT 0